[package]
name = "wordlist-dedup"
version = "0.1.1"
authors = ["Michael Sasser <Michael@MichaelSasser.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indicatif = "0.15.0"
