[package]
name = "wordlist-undup"
version = "0.1.0"
authors = ["Michael Sasser <Michael@MichaelSasser.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indicatif = "0.13.0"
