#use_small_heuristics = "Max"
max_width = 79
indent_style = "Block"
reorder_imports = true
edition = "2021"
format_strings = true
hex_literal_case = "Upper"
imports_layout = "Vertical"
match_block_trailing_comma = true
imports_granularity = "One"
newline_style = "Unix"
reorder_impl_items = true
group_imports = "StdExternalCrate"
reorder_modules = true
# struct_field_align_threshold = 20
use_field_init_shorthand = true
use_try_shorthand = true
